
//ProblemSet9.1.c.
// Write a prgram that generates 1 second long noise using the rand() function from stdlib.h.
// Save the result in the wave file named noise.wav.
// For this problem set, make sure to keep the signal range to -1 ~ 1 range and use the sf_write_float function to write the result.
// Use the RAND_MAX constant from stdlib.h to map the value generated by rand() to the -1 ~ 1 audio range.
// Use the srand() and time function to seed the random number generator before generating noise.

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <memory.h>
#include <sndfile.h>


//Define constant paramenters

#define kSampleRate 44100
#define kSec 1 //program that generates 1 second long 
#define kNumFrames kSampleRate * kSec //Frames = samplerate * time
#define kNumChannels 2
#define kFormat (SF_FORMAT_WAV| SF_FORMAT_PCM_24)
#define kFileName "noise.wav" // Save the result in the wave file named noise.wav.
#define kNumHarmonics 32


//Main Func starts

int main(){


//Variables 

SNDFILE *myfile; //File
SF_INFO fileInfo; //Information of the File
double *buffer; //Where to store


//Parameters of the noise 
double randomAmp = (float)rand()/RAND_MAX;
double amplitude = randomAmp;

double randomFreq
double frequency = 440.0; //in Hz
//Computer doesn't read seconds --> Frequency needs to be transformed
frequency = frequency / kSampleRate;

//Allocate using malloc

buffer = calloc(kNumFrames * kNumChannels, sizeof(double)); //Frames represent length of the file

//Check
if (!buffer){
    printf("Error\n");
    return 1;
}


//Memset to set all of the memory space to 0

memset(&fileInfo, 0, sizeof(SF_INFO));


//setting Properties of the Audio File
//Assigns

fileInfo.samplerate = kSampleRate;
fileInfo.frames = kNumFrames;
fileInfo.channels = kNumChannels;
fileInfo.format = kFormat;


//Time to open the file!

myfile = sf_open (kFileName, SFM_WRITE, &fileInfo);

//Check
if (!myfile){
    printf("Error!\n");
    return 1;
}

//Time to Write!

for (int t = 0; t < kNumFrames; t++){ //t is current time

    for (int h = 0; i < kSampleRate; i++){
        buffer[h] = (rand()/ (float)RAND_MAX - 0.5) *2;
    }


    //Put each harmonic into the buffer
      for (int a = 0; a <kNumChannels; a++){
        buffer [kNumChannels * t + a] += sample; //Add all of it and initialize buffer to 0 with calloc
    }
    }

}



//Finally --> Write Sine Wave into Audio File

sf_count_t count = sf_write_float(myfile, buffer, kNumFrames * kNumChannels);

if (count != kNumChannels * kNumFrames){
    printf("Error!\n");
    
}


//Close
sf_close(myfile);
free(buffer);











return 0;
}